// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RectangleApp.Data;

namespace RectangleApp.Migrations
{
    [DbContext(typeof(DBInteractor))]
    partial class DBInteractorModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("RectangleApp.Models.Rectangle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("height")
                        .HasColumnType("REAL");

                    b.Property<float>("width")
                        .HasColumnType("REAL");

                    b.Property<float>("x")
                        .HasColumnType("REAL");

                    b.Property<float>("y")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("rectangles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            height = 4f,
                            width = 2f,
                            x = 1f,
                            y = 1f
                        },
                        new
                        {
                            Id = 2L,
                            height = 4f,
                            width = 2f,
                            x = 2f,
                            y = 2f
                        },
                        new
                        {
                            Id = 3L,
                            height = 4f,
                            width = 2f,
                            x = 3f,
                            y = 3f
                        },
                        new
                        {
                            Id = 4L,
                            height = 4f,
                            width = 2f,
                            x = 4f,
                            y = 4f
                        },
                        new
                        {
                            Id = 5L,
                            height = 4f,
                            width = 2f,
                            x = 5f,
                            y = 5f
                        },
                        new
                        {
                            Id = 6L,
                            height = 4f,
                            width = 2f,
                            x = 6f,
                            y = 6f
                        },
                        new
                        {
                            Id = 7L,
                            height = 4f,
                            width = 2f,
                            x = 7f,
                            y = 7f
                        },
                        new
                        {
                            Id = 8L,
                            height = 4f,
                            width = 2f,
                            x = 8f,
                            y = 8f
                        },
                        new
                        {
                            Id = 9L,
                            height = 4f,
                            width = 2f,
                            x = 9f,
                            y = 9f
                        },
                        new
                        {
                            Id = 10L,
                            height = 4f,
                            width = 2f,
                            x = 10f,
                            y = 10f
                        },
                        new
                        {
                            Id = 11L,
                            height = 4f,
                            width = 2f,
                            x = 11f,
                            y = 11f
                        },
                        new
                        {
                            Id = 12L,
                            height = 4f,
                            width = 2f,
                            x = 12f,
                            y = 12f
                        },
                        new
                        {
                            Id = 13L,
                            height = 4f,
                            width = 2f,
                            x = 13f,
                            y = 13f
                        },
                        new
                        {
                            Id = 14L,
                            height = 4f,
                            width = 2f,
                            x = 14f,
                            y = 14f
                        },
                        new
                        {
                            Id = 15L,
                            height = 4f,
                            width = 2f,
                            x = 15f,
                            y = 15f
                        },
                        new
                        {
                            Id = 16L,
                            height = 4f,
                            width = 2f,
                            x = 16f,
                            y = 16f
                        },
                        new
                        {
                            Id = 17L,
                            height = 4f,
                            width = 2f,
                            x = 17f,
                            y = 17f
                        },
                        new
                        {
                            Id = 18L,
                            height = 4f,
                            width = 2f,
                            x = 18f,
                            y = 18f
                        },
                        new
                        {
                            Id = 19L,
                            height = 4f,
                            width = 2f,
                            x = 19f,
                            y = 19f
                        },
                        new
                        {
                            Id = 20L,
                            height = 4f,
                            width = 2f,
                            x = 20f,
                            y = 20f
                        },
                        new
                        {
                            Id = 21L,
                            height = 4f,
                            width = 2f,
                            x = 21f,
                            y = 21f
                        },
                        new
                        {
                            Id = 22L,
                            height = 4f,
                            width = 2f,
                            x = 22f,
                            y = 22f
                        },
                        new
                        {
                            Id = 23L,
                            height = 4f,
                            width = 2f,
                            x = 23f,
                            y = 23f
                        },
                        new
                        {
                            Id = 24L,
                            height = 4f,
                            width = 2f,
                            x = 24f,
                            y = 24f
                        },
                        new
                        {
                            Id = 25L,
                            height = 4f,
                            width = 2f,
                            x = 25f,
                            y = 25f
                        },
                        new
                        {
                            Id = 26L,
                            height = 4f,
                            width = 2f,
                            x = 26f,
                            y = 26f
                        },
                        new
                        {
                            Id = 27L,
                            height = 4f,
                            width = 2f,
                            x = 27f,
                            y = 27f
                        },
                        new
                        {
                            Id = 28L,
                            height = 4f,
                            width = 2f,
                            x = 28f,
                            y = 28f
                        },
                        new
                        {
                            Id = 29L,
                            height = 4f,
                            width = 2f,
                            x = 29f,
                            y = 29f
                        },
                        new
                        {
                            Id = 30L,
                            height = 4f,
                            width = 2f,
                            x = 30f,
                            y = 30f
                        },
                        new
                        {
                            Id = 31L,
                            height = 4f,
                            width = 2f,
                            x = 31f,
                            y = 31f
                        },
                        new
                        {
                            Id = 32L,
                            height = 4f,
                            width = 2f,
                            x = 32f,
                            y = 32f
                        },
                        new
                        {
                            Id = 33L,
                            height = 4f,
                            width = 2f,
                            x = 33f,
                            y = 33f
                        },
                        new
                        {
                            Id = 34L,
                            height = 4f,
                            width = 2f,
                            x = 34f,
                            y = 34f
                        },
                        new
                        {
                            Id = 35L,
                            height = 4f,
                            width = 2f,
                            x = 35f,
                            y = 35f
                        },
                        new
                        {
                            Id = 36L,
                            height = 4f,
                            width = 2f,
                            x = 36f,
                            y = 36f
                        },
                        new
                        {
                            Id = 37L,
                            height = 4f,
                            width = 2f,
                            x = 37f,
                            y = 37f
                        },
                        new
                        {
                            Id = 38L,
                            height = 4f,
                            width = 2f,
                            x = 38f,
                            y = 38f
                        },
                        new
                        {
                            Id = 39L,
                            height = 4f,
                            width = 2f,
                            x = 39f,
                            y = 39f
                        },
                        new
                        {
                            Id = 40L,
                            height = 4f,
                            width = 2f,
                            x = 40f,
                            y = 40f
                        },
                        new
                        {
                            Id = 41L,
                            height = 4f,
                            width = 2f,
                            x = 41f,
                            y = 41f
                        },
                        new
                        {
                            Id = 42L,
                            height = 4f,
                            width = 2f,
                            x = 42f,
                            y = 42f
                        },
                        new
                        {
                            Id = 43L,
                            height = 4f,
                            width = 2f,
                            x = 43f,
                            y = 43f
                        },
                        new
                        {
                            Id = 44L,
                            height = 4f,
                            width = 2f,
                            x = 44f,
                            y = 44f
                        },
                        new
                        {
                            Id = 45L,
                            height = 4f,
                            width = 2f,
                            x = 45f,
                            y = 45f
                        },
                        new
                        {
                            Id = 46L,
                            height = 4f,
                            width = 2f,
                            x = 46f,
                            y = 46f
                        },
                        new
                        {
                            Id = 47L,
                            height = 4f,
                            width = 2f,
                            x = 47f,
                            y = 47f
                        },
                        new
                        {
                            Id = 48L,
                            height = 4f,
                            width = 2f,
                            x = 48f,
                            y = 48f
                        },
                        new
                        {
                            Id = 49L,
                            height = 4f,
                            width = 2f,
                            x = 49f,
                            y = 49f
                        },
                        new
                        {
                            Id = 50L,
                            height = 4f,
                            width = 2f,
                            x = 50f,
                            y = 50f
                        },
                        new
                        {
                            Id = 51L,
                            height = 4f,
                            width = 2f,
                            x = 51f,
                            y = 51f
                        },
                        new
                        {
                            Id = 52L,
                            height = 4f,
                            width = 2f,
                            x = 52f,
                            y = 52f
                        },
                        new
                        {
                            Id = 53L,
                            height = 4f,
                            width = 2f,
                            x = 53f,
                            y = 53f
                        },
                        new
                        {
                            Id = 54L,
                            height = 4f,
                            width = 2f,
                            x = 54f,
                            y = 54f
                        },
                        new
                        {
                            Id = 55L,
                            height = 4f,
                            width = 2f,
                            x = 55f,
                            y = 55f
                        },
                        new
                        {
                            Id = 56L,
                            height = 4f,
                            width = 2f,
                            x = 56f,
                            y = 56f
                        },
                        new
                        {
                            Id = 57L,
                            height = 4f,
                            width = 2f,
                            x = 57f,
                            y = 57f
                        },
                        new
                        {
                            Id = 58L,
                            height = 4f,
                            width = 2f,
                            x = 58f,
                            y = 58f
                        },
                        new
                        {
                            Id = 59L,
                            height = 4f,
                            width = 2f,
                            x = 59f,
                            y = 59f
                        },
                        new
                        {
                            Id = 60L,
                            height = 4f,
                            width = 2f,
                            x = 60f,
                            y = 60f
                        },
                        new
                        {
                            Id = 61L,
                            height = 4f,
                            width = 2f,
                            x = 61f,
                            y = 61f
                        },
                        new
                        {
                            Id = 62L,
                            height = 4f,
                            width = 2f,
                            x = 62f,
                            y = 62f
                        },
                        new
                        {
                            Id = 63L,
                            height = 4f,
                            width = 2f,
                            x = 63f,
                            y = 63f
                        },
                        new
                        {
                            Id = 64L,
                            height = 4f,
                            width = 2f,
                            x = 64f,
                            y = 64f
                        },
                        new
                        {
                            Id = 65L,
                            height = 4f,
                            width = 2f,
                            x = 65f,
                            y = 65f
                        },
                        new
                        {
                            Id = 66L,
                            height = 4f,
                            width = 2f,
                            x = 66f,
                            y = 66f
                        },
                        new
                        {
                            Id = 67L,
                            height = 4f,
                            width = 2f,
                            x = 67f,
                            y = 67f
                        },
                        new
                        {
                            Id = 68L,
                            height = 4f,
                            width = 2f,
                            x = 68f,
                            y = 68f
                        },
                        new
                        {
                            Id = 69L,
                            height = 4f,
                            width = 2f,
                            x = 69f,
                            y = 69f
                        },
                        new
                        {
                            Id = 70L,
                            height = 4f,
                            width = 2f,
                            x = 70f,
                            y = 70f
                        },
                        new
                        {
                            Id = 71L,
                            height = 4f,
                            width = 2f,
                            x = 71f,
                            y = 71f
                        },
                        new
                        {
                            Id = 72L,
                            height = 4f,
                            width = 2f,
                            x = 72f,
                            y = 72f
                        },
                        new
                        {
                            Id = 73L,
                            height = 4f,
                            width = 2f,
                            x = 73f,
                            y = 73f
                        },
                        new
                        {
                            Id = 74L,
                            height = 4f,
                            width = 2f,
                            x = 74f,
                            y = 74f
                        },
                        new
                        {
                            Id = 75L,
                            height = 4f,
                            width = 2f,
                            x = 75f,
                            y = 75f
                        },
                        new
                        {
                            Id = 76L,
                            height = 4f,
                            width = 2f,
                            x = 76f,
                            y = 76f
                        },
                        new
                        {
                            Id = 77L,
                            height = 4f,
                            width = 2f,
                            x = 77f,
                            y = 77f
                        },
                        new
                        {
                            Id = 78L,
                            height = 4f,
                            width = 2f,
                            x = 78f,
                            y = 78f
                        },
                        new
                        {
                            Id = 79L,
                            height = 4f,
                            width = 2f,
                            x = 79f,
                            y = 79f
                        },
                        new
                        {
                            Id = 80L,
                            height = 4f,
                            width = 2f,
                            x = 80f,
                            y = 80f
                        },
                        new
                        {
                            Id = 81L,
                            height = 4f,
                            width = 2f,
                            x = 81f,
                            y = 81f
                        },
                        new
                        {
                            Id = 82L,
                            height = 4f,
                            width = 2f,
                            x = 82f,
                            y = 82f
                        },
                        new
                        {
                            Id = 83L,
                            height = 4f,
                            width = 2f,
                            x = 83f,
                            y = 83f
                        },
                        new
                        {
                            Id = 84L,
                            height = 4f,
                            width = 2f,
                            x = 84f,
                            y = 84f
                        },
                        new
                        {
                            Id = 85L,
                            height = 4f,
                            width = 2f,
                            x = 85f,
                            y = 85f
                        },
                        new
                        {
                            Id = 86L,
                            height = 4f,
                            width = 2f,
                            x = 86f,
                            y = 86f
                        },
                        new
                        {
                            Id = 87L,
                            height = 4f,
                            width = 2f,
                            x = 87f,
                            y = 87f
                        },
                        new
                        {
                            Id = 88L,
                            height = 4f,
                            width = 2f,
                            x = 88f,
                            y = 88f
                        },
                        new
                        {
                            Id = 89L,
                            height = 4f,
                            width = 2f,
                            x = 89f,
                            y = 89f
                        },
                        new
                        {
                            Id = 90L,
                            height = 4f,
                            width = 2f,
                            x = 90f,
                            y = 90f
                        },
                        new
                        {
                            Id = 91L,
                            height = 4f,
                            width = 2f,
                            x = 91f,
                            y = 91f
                        },
                        new
                        {
                            Id = 92L,
                            height = 4f,
                            width = 2f,
                            x = 92f,
                            y = 92f
                        },
                        new
                        {
                            Id = 93L,
                            height = 4f,
                            width = 2f,
                            x = 93f,
                            y = 93f
                        },
                        new
                        {
                            Id = 94L,
                            height = 4f,
                            width = 2f,
                            x = 94f,
                            y = 94f
                        },
                        new
                        {
                            Id = 95L,
                            height = 4f,
                            width = 2f,
                            x = 95f,
                            y = 95f
                        },
                        new
                        {
                            Id = 96L,
                            height = 4f,
                            width = 2f,
                            x = 96f,
                            y = 96f
                        },
                        new
                        {
                            Id = 97L,
                            height = 4f,
                            width = 2f,
                            x = 97f,
                            y = 97f
                        },
                        new
                        {
                            Id = 98L,
                            height = 4f,
                            width = 2f,
                            x = 98f,
                            y = 98f
                        },
                        new
                        {
                            Id = 99L,
                            height = 4f,
                            width = 2f,
                            x = 99f,
                            y = 99f
                        },
                        new
                        {
                            Id = 100L,
                            height = 4f,
                            width = 2f,
                            x = 100f,
                            y = 100f
                        },
                        new
                        {
                            Id = 101L,
                            height = 4f,
                            width = 2f,
                            x = 101f,
                            y = 101f
                        },
                        new
                        {
                            Id = 102L,
                            height = 4f,
                            width = 2f,
                            x = 102f,
                            y = 102f
                        },
                        new
                        {
                            Id = 103L,
                            height = 4f,
                            width = 2f,
                            x = 103f,
                            y = 103f
                        },
                        new
                        {
                            Id = 104L,
                            height = 4f,
                            width = 2f,
                            x = 104f,
                            y = 104f
                        },
                        new
                        {
                            Id = 105L,
                            height = 4f,
                            width = 2f,
                            x = 105f,
                            y = 105f
                        },
                        new
                        {
                            Id = 106L,
                            height = 4f,
                            width = 2f,
                            x = 106f,
                            y = 106f
                        },
                        new
                        {
                            Id = 107L,
                            height = 4f,
                            width = 2f,
                            x = 107f,
                            y = 107f
                        },
                        new
                        {
                            Id = 108L,
                            height = 4f,
                            width = 2f,
                            x = 108f,
                            y = 108f
                        },
                        new
                        {
                            Id = 109L,
                            height = 4f,
                            width = 2f,
                            x = 109f,
                            y = 109f
                        },
                        new
                        {
                            Id = 110L,
                            height = 4f,
                            width = 2f,
                            x = 110f,
                            y = 110f
                        },
                        new
                        {
                            Id = 111L,
                            height = 4f,
                            width = 2f,
                            x = 111f,
                            y = 111f
                        },
                        new
                        {
                            Id = 112L,
                            height = 4f,
                            width = 2f,
                            x = 112f,
                            y = 112f
                        },
                        new
                        {
                            Id = 113L,
                            height = 4f,
                            width = 2f,
                            x = 113f,
                            y = 113f
                        },
                        new
                        {
                            Id = 114L,
                            height = 4f,
                            width = 2f,
                            x = 114f,
                            y = 114f
                        },
                        new
                        {
                            Id = 115L,
                            height = 4f,
                            width = 2f,
                            x = 115f,
                            y = 115f
                        },
                        new
                        {
                            Id = 116L,
                            height = 4f,
                            width = 2f,
                            x = 116f,
                            y = 116f
                        },
                        new
                        {
                            Id = 117L,
                            height = 4f,
                            width = 2f,
                            x = 117f,
                            y = 117f
                        },
                        new
                        {
                            Id = 118L,
                            height = 4f,
                            width = 2f,
                            x = 118f,
                            y = 118f
                        },
                        new
                        {
                            Id = 119L,
                            height = 4f,
                            width = 2f,
                            x = 119f,
                            y = 119f
                        },
                        new
                        {
                            Id = 120L,
                            height = 4f,
                            width = 2f,
                            x = 120f,
                            y = 120f
                        },
                        new
                        {
                            Id = 121L,
                            height = 4f,
                            width = 2f,
                            x = 121f,
                            y = 121f
                        },
                        new
                        {
                            Id = 122L,
                            height = 4f,
                            width = 2f,
                            x = 122f,
                            y = 122f
                        },
                        new
                        {
                            Id = 123L,
                            height = 4f,
                            width = 2f,
                            x = 123f,
                            y = 123f
                        },
                        new
                        {
                            Id = 124L,
                            height = 4f,
                            width = 2f,
                            x = 124f,
                            y = 124f
                        },
                        new
                        {
                            Id = 125L,
                            height = 4f,
                            width = 2f,
                            x = 125f,
                            y = 125f
                        },
                        new
                        {
                            Id = 126L,
                            height = 4f,
                            width = 2f,
                            x = 126f,
                            y = 126f
                        },
                        new
                        {
                            Id = 127L,
                            height = 4f,
                            width = 2f,
                            x = 127f,
                            y = 127f
                        },
                        new
                        {
                            Id = 128L,
                            height = 4f,
                            width = 2f,
                            x = 128f,
                            y = 128f
                        },
                        new
                        {
                            Id = 129L,
                            height = 4f,
                            width = 2f,
                            x = 129f,
                            y = 129f
                        },
                        new
                        {
                            Id = 130L,
                            height = 4f,
                            width = 2f,
                            x = 130f,
                            y = 130f
                        },
                        new
                        {
                            Id = 131L,
                            height = 4f,
                            width = 2f,
                            x = 131f,
                            y = 131f
                        },
                        new
                        {
                            Id = 132L,
                            height = 4f,
                            width = 2f,
                            x = 132f,
                            y = 132f
                        },
                        new
                        {
                            Id = 133L,
                            height = 4f,
                            width = 2f,
                            x = 133f,
                            y = 133f
                        },
                        new
                        {
                            Id = 134L,
                            height = 4f,
                            width = 2f,
                            x = 134f,
                            y = 134f
                        },
                        new
                        {
                            Id = 135L,
                            height = 4f,
                            width = 2f,
                            x = 135f,
                            y = 135f
                        },
                        new
                        {
                            Id = 136L,
                            height = 4f,
                            width = 2f,
                            x = 136f,
                            y = 136f
                        },
                        new
                        {
                            Id = 137L,
                            height = 4f,
                            width = 2f,
                            x = 137f,
                            y = 137f
                        },
                        new
                        {
                            Id = 138L,
                            height = 4f,
                            width = 2f,
                            x = 138f,
                            y = 138f
                        },
                        new
                        {
                            Id = 139L,
                            height = 4f,
                            width = 2f,
                            x = 139f,
                            y = 139f
                        },
                        new
                        {
                            Id = 140L,
                            height = 4f,
                            width = 2f,
                            x = 140f,
                            y = 140f
                        },
                        new
                        {
                            Id = 141L,
                            height = 4f,
                            width = 2f,
                            x = 141f,
                            y = 141f
                        },
                        new
                        {
                            Id = 142L,
                            height = 4f,
                            width = 2f,
                            x = 142f,
                            y = 142f
                        },
                        new
                        {
                            Id = 143L,
                            height = 4f,
                            width = 2f,
                            x = 143f,
                            y = 143f
                        },
                        new
                        {
                            Id = 144L,
                            height = 4f,
                            width = 2f,
                            x = 144f,
                            y = 144f
                        },
                        new
                        {
                            Id = 145L,
                            height = 4f,
                            width = 2f,
                            x = 145f,
                            y = 145f
                        },
                        new
                        {
                            Id = 146L,
                            height = 4f,
                            width = 2f,
                            x = 146f,
                            y = 146f
                        },
                        new
                        {
                            Id = 147L,
                            height = 4f,
                            width = 2f,
                            x = 147f,
                            y = 147f
                        },
                        new
                        {
                            Id = 148L,
                            height = 4f,
                            width = 2f,
                            x = 148f,
                            y = 148f
                        },
                        new
                        {
                            Id = 149L,
                            height = 4f,
                            width = 2f,
                            x = 149f,
                            y = 149f
                        },
                        new
                        {
                            Id = 150L,
                            height = 4f,
                            width = 2f,
                            x = 150f,
                            y = 150f
                        },
                        new
                        {
                            Id = 151L,
                            height = 4f,
                            width = 2f,
                            x = 151f,
                            y = 151f
                        },
                        new
                        {
                            Id = 152L,
                            height = 4f,
                            width = 2f,
                            x = 152f,
                            y = 152f
                        },
                        new
                        {
                            Id = 153L,
                            height = 4f,
                            width = 2f,
                            x = 153f,
                            y = 153f
                        },
                        new
                        {
                            Id = 154L,
                            height = 4f,
                            width = 2f,
                            x = 154f,
                            y = 154f
                        },
                        new
                        {
                            Id = 155L,
                            height = 4f,
                            width = 2f,
                            x = 155f,
                            y = 155f
                        },
                        new
                        {
                            Id = 156L,
                            height = 4f,
                            width = 2f,
                            x = 156f,
                            y = 156f
                        },
                        new
                        {
                            Id = 157L,
                            height = 4f,
                            width = 2f,
                            x = 157f,
                            y = 157f
                        },
                        new
                        {
                            Id = 158L,
                            height = 4f,
                            width = 2f,
                            x = 158f,
                            y = 158f
                        },
                        new
                        {
                            Id = 159L,
                            height = 4f,
                            width = 2f,
                            x = 159f,
                            y = 159f
                        },
                        new
                        {
                            Id = 160L,
                            height = 4f,
                            width = 2f,
                            x = 160f,
                            y = 160f
                        },
                        new
                        {
                            Id = 161L,
                            height = 4f,
                            width = 2f,
                            x = 161f,
                            y = 161f
                        },
                        new
                        {
                            Id = 162L,
                            height = 4f,
                            width = 2f,
                            x = 162f,
                            y = 162f
                        },
                        new
                        {
                            Id = 163L,
                            height = 4f,
                            width = 2f,
                            x = 163f,
                            y = 163f
                        },
                        new
                        {
                            Id = 164L,
                            height = 4f,
                            width = 2f,
                            x = 164f,
                            y = 164f
                        },
                        new
                        {
                            Id = 165L,
                            height = 4f,
                            width = 2f,
                            x = 165f,
                            y = 165f
                        },
                        new
                        {
                            Id = 166L,
                            height = 4f,
                            width = 2f,
                            x = 166f,
                            y = 166f
                        },
                        new
                        {
                            Id = 167L,
                            height = 4f,
                            width = 2f,
                            x = 167f,
                            y = 167f
                        },
                        new
                        {
                            Id = 168L,
                            height = 4f,
                            width = 2f,
                            x = 168f,
                            y = 168f
                        },
                        new
                        {
                            Id = 169L,
                            height = 4f,
                            width = 2f,
                            x = 169f,
                            y = 169f
                        },
                        new
                        {
                            Id = 170L,
                            height = 4f,
                            width = 2f,
                            x = 170f,
                            y = 170f
                        },
                        new
                        {
                            Id = 171L,
                            height = 4f,
                            width = 2f,
                            x = 171f,
                            y = 171f
                        },
                        new
                        {
                            Id = 172L,
                            height = 4f,
                            width = 2f,
                            x = 172f,
                            y = 172f
                        },
                        new
                        {
                            Id = 173L,
                            height = 4f,
                            width = 2f,
                            x = 173f,
                            y = 173f
                        },
                        new
                        {
                            Id = 174L,
                            height = 4f,
                            width = 2f,
                            x = 174f,
                            y = 174f
                        },
                        new
                        {
                            Id = 175L,
                            height = 4f,
                            width = 2f,
                            x = 175f,
                            y = 175f
                        },
                        new
                        {
                            Id = 176L,
                            height = 4f,
                            width = 2f,
                            x = 176f,
                            y = 176f
                        },
                        new
                        {
                            Id = 177L,
                            height = 4f,
                            width = 2f,
                            x = 177f,
                            y = 177f
                        },
                        new
                        {
                            Id = 178L,
                            height = 4f,
                            width = 2f,
                            x = 178f,
                            y = 178f
                        },
                        new
                        {
                            Id = 179L,
                            height = 4f,
                            width = 2f,
                            x = 179f,
                            y = 179f
                        },
                        new
                        {
                            Id = 180L,
                            height = 4f,
                            width = 2f,
                            x = 180f,
                            y = 180f
                        },
                        new
                        {
                            Id = 181L,
                            height = 4f,
                            width = 2f,
                            x = 181f,
                            y = 181f
                        },
                        new
                        {
                            Id = 182L,
                            height = 4f,
                            width = 2f,
                            x = 182f,
                            y = 182f
                        },
                        new
                        {
                            Id = 183L,
                            height = 4f,
                            width = 2f,
                            x = 183f,
                            y = 183f
                        },
                        new
                        {
                            Id = 184L,
                            height = 4f,
                            width = 2f,
                            x = 184f,
                            y = 184f
                        },
                        new
                        {
                            Id = 185L,
                            height = 4f,
                            width = 2f,
                            x = 185f,
                            y = 185f
                        },
                        new
                        {
                            Id = 186L,
                            height = 4f,
                            width = 2f,
                            x = 186f,
                            y = 186f
                        },
                        new
                        {
                            Id = 187L,
                            height = 4f,
                            width = 2f,
                            x = 187f,
                            y = 187f
                        },
                        new
                        {
                            Id = 188L,
                            height = 4f,
                            width = 2f,
                            x = 188f,
                            y = 188f
                        },
                        new
                        {
                            Id = 189L,
                            height = 4f,
                            width = 2f,
                            x = 189f,
                            y = 189f
                        },
                        new
                        {
                            Id = 190L,
                            height = 4f,
                            width = 2f,
                            x = 190f,
                            y = 190f
                        },
                        new
                        {
                            Id = 191L,
                            height = 4f,
                            width = 2f,
                            x = 191f,
                            y = 191f
                        },
                        new
                        {
                            Id = 192L,
                            height = 4f,
                            width = 2f,
                            x = 192f,
                            y = 192f
                        },
                        new
                        {
                            Id = 193L,
                            height = 4f,
                            width = 2f,
                            x = 193f,
                            y = 193f
                        },
                        new
                        {
                            Id = 194L,
                            height = 4f,
                            width = 2f,
                            x = 194f,
                            y = 194f
                        },
                        new
                        {
                            Id = 195L,
                            height = 4f,
                            width = 2f,
                            x = 195f,
                            y = 195f
                        },
                        new
                        {
                            Id = 196L,
                            height = 4f,
                            width = 2f,
                            x = 196f,
                            y = 196f
                        },
                        new
                        {
                            Id = 197L,
                            height = 4f,
                            width = 2f,
                            x = 197f,
                            y = 197f
                        },
                        new
                        {
                            Id = 198L,
                            height = 4f,
                            width = 2f,
                            x = 198f,
                            y = 198f
                        },
                        new
                        {
                            Id = 199L,
                            height = 4f,
                            width = 2f,
                            x = 199f,
                            y = 199f
                        },
                        new
                        {
                            Id = 200L,
                            height = 4f,
                            width = 2f,
                            x = 200f,
                            y = 200f
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
